const createNextIntlPlugin = require('next-intl/plugin');
const withNextIntl = createNextIntlPlugin();

const nextConfig = {
  compress: true,
  experimental: {
    serverActions: { bodySizeLimit: '20mb' },
    optimizePackageImports: ['next-intl'],
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    minimumCacheTTL: 60 * 60 * 24 * 30,
  },
  async redirects() {
    return [
      { source: '/despre',         destination: '/ro/despre',         permanent: true },
      { source: '/about',          destination: '/en/about',          permanent: true },
      { source: '/ueber-uns',      destination: '/de/ueber-uns',      permanent: true },
      { source: '/a-propos',       destination: '/fr/a-propos',       permanent: true },
      { source: '/sobre-nosotros', destination: '/es/sobre-nosotros', permanent: true },
      { source: '/chi-siamo',      destination: '/it/chi-siamo',      permanent: true },
      { source: '/gdpr',             destination: '/ro/gdpr',           permanent: true },
      { source: '/privacy-policy',   destination: '/en/privacy-policy', permanent: true },
      { source: '/datenschutz',      destination: '/de/datenschutz',    permanent: true },
      { source: '/contact',          destination: '/ro/contact',        permanent: true },
      { source: '/blog',             destination: '/ro/blog',           permanent: true },
      { source: '/servicii',         destination: '/ro/servicii',       permanent: true },
      { source: '/accesorii',        destination: '/ro/accesorii',      permanent: true },
      // Fix dublu slash URLs (crawled de Google dar neindexate)
      { source: '/en//tamplarie-pvc',  destination: '/en/pvc-windows',            permanent: true },
      { source: '/en//pvc-windows',    destination: '/en/pvc-windows',            permanent: true },
      // === Redirecturi folder parinte gresit → corect (95 URL-uri neindexate) ===
      // accesorii
      { source: '/en/accesorii/pvc-renovation-frame', destination: '/en/accessories/pvc-renovation-frame', permanent: true },
      { source: '/de/accesorii/pvc-renovierungsrahmen', destination: '/de/zubehoer/pvc-renovierungsrahmen', permanent: true },
      { source: '/fr/accesorii/cadre-renovation-pvc', destination: '/fr/accessoires/cadre-renovation-pvc', permanent: true },
      { source: '/es/accesorii/marco-renovacion-pvc', destination: '/es/accesorios/marco-renovacion-pvc', permanent: true },
      { source: '/it/accesorii/telaio-ristrutturazione-pvc', destination: '/it/accessori/telaio-ristrutturazione-pvc', permanent: true },
      { source: '/en/accesorii/interior-pvc-windowsills-exterior-aluminium-sills', destination: '/en/accessories/interior-pvc-windowsills-exterior-aluminium-sills', permanent: true },
      { source: '/de/accesorii/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', destination: '/de/zubehoer/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', permanent: true },
      { source: '/fr/accesorii/appuis-fenetre-interieurs-pvc-exterieurs-aluminium', destination: '/fr/accessoires/appuis-fenetre-interieurs-pvc-exterieurs-aluminium', permanent: true },
      { source: '/es/accesorii/alfeizares-interiores-pvc-exteriores-aluminio', destination: '/es/accesorios/alfeizares-interiores-pvc-exteriores-aluminio', permanent: true },
      { source: '/it/accesorii/davanzali-interni-pvc-esterni-alluminio', destination: '/it/accessori/davanzali-interni-pvc-esterni-alluminio', permanent: true },
      { source: '/en/accesorii/aereco-hygro-adjustable-ventilation-grille', destination: '/en/accessories/aereco-hygro-adjustable-ventilation-grille', permanent: true },
      { source: '/de/accesorii/aereco-hygroregelbare-lueftungsgitter', destination: '/de/zubehoer/aereco-hygroregelbare-lueftungsgitter', permanent: true },
      { source: '/fr/accesorii/grille-hygroreglable-aereco-ventilation', destination: '/fr/accessoires/grille-hygroreglable-aereco-ventilation', permanent: true },
      { source: '/es/accesorii/rejilla-higrorreglable-aereco-ventilacion', destination: '/es/accesorios/rejilla-higrorreglable-aereco-ventilacion', permanent: true },
      { source: '/it/accesorii/griglia-igroregolab-aereco-ventilazione', destination: '/it/accessori/griglia-igroregolab-aereco-ventilazione', permanent: true },
      { source: '/en/accesorii/somfy-automation-shutters-pergolas', destination: '/en/accessories/somfy-automation-shutters-pergolas', permanent: true },
      { source: '/de/accesorii/somfy-automatisierung-rolllaeden-pergolen', destination: '/de/zubehoer/somfy-automatisierung-rolllaeden-pergolen', permanent: true },
      { source: '/fr/accesorii/automatisation-somfy-volets-pergolas', destination: '/fr/accessoires/automatisation-somfy-volets-pergolas', permanent: true },
      { source: '/es/accesorii/automatizacion-somfy-persianas-pergolas', destination: '/es/accesorios/automatizacion-somfy-persianas-pergolas', permanent: true },
      { source: '/it/accesorii/automazione-somfy-tapparelle-pergole', destination: '/it/accessori/automazione-somfy-tapparelle-pergole', permanent: true },
      // produse-aluminiu
      { source: '/en/produse-aluminiu/alumil-s77-supreme-aluminium-system', destination: '/en/products-alu/alumil-s77-supreme-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s77-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-s77-supreme-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s77-supreme', destination: '/fr/produits-alu/systeme-aluminium-alumil-s77-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s77-supreme', destination: '/es/productos-alu/sistema-aluminio-alumil-s77-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s77-supreme', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s77-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s67-smartia-aluminium-system', destination: '/en/products-alu/alumil-s67-smartia-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s67-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-s67-smartia-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s67-smartia', destination: '/fr/produits-alu/systeme-aluminium-alumil-s67-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s67-smartia', destination: '/es/productos-alu/sistema-aluminio-alumil-s67-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s67-smartia', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s67-smartia', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s700-supreme-aluminium-system', destination: '/en/products-alu/alumil-s700-supreme-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s700-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-s700-supreme-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s700-supreme', destination: '/fr/produits-alu/systeme-aluminium-alumil-s700-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s700-supreme', destination: '/es/productos-alu/sistema-aluminio-alumil-s700-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s700-supreme', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s700-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s350-smartia-aluminium-system', destination: '/en/products-alu/alumil-s350-smartia-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s350-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-s350-smartia-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s350-smartia', destination: '/fr/produits-alu/systeme-aluminium-alumil-s350-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s350-smartia', destination: '/es/productos-alu/sistema-aluminio-alumil-s350-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s350-smartia', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s350-smartia', permanent: true },
      { source: '/en/produse-aluminiu/alumil-sf85-supreme-aluminium-system', destination: '/en/products-alu/alumil-sf85-supreme-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-sf85-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-sf85-supreme-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-sf85-supreme', destination: '/fr/produits-alu/systeme-aluminium-alumil-sf85-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-sf85-supreme', destination: '/es/productos-alu/sistema-aluminio-alumil-sf85-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-sf85-supreme', destination: '/it/prodotti-alu/sistema-alluminio-alumil-sf85-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-m19800-smartia-aluminium-system', destination: '/en/products-alu/alumil-m19800-smartia-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-m19800-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-m19800-smartia-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-m19800-smartia', destination: '/fr/produits-alu/systeme-aluminium-alumil-m19800-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-m19800-smartia', destination: '/es/productos-alu/sistema-aluminio-alumil-m19800-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-m19800-smartia', destination: '/it/prodotti-alu/sistema-alluminio-alumil-m19800-smartia', permanent: true },
      // umbrire
      { source: '/en/umbrire/aluminium-external-roller-shutters', destination: '/en/shading-systems/aluminium-external-roller-shutters', permanent: true },
      { source: '/de/umbrire/aluminium-aussenrollladen', destination: '/de/beschattungssysteme/aluminium-aussenrollladen', permanent: true },
      { source: '/fr/umbrire/volets-roulants-aluminium-exterieurs', destination: '/fr/systemes-occultation/volets-roulants-aluminium-exterieurs', permanent: true },
      { source: '/es/umbrire/persianas-exteriores-aluminio', destination: '/es/sistemas-sombreado/persianas-exteriores-aluminio', permanent: true },
      { source: '/it/umbrire/tapparelle-esterne-alluminio', destination: '/it/sistemi-oscuramento/tapparelle-esterne-alluminio', permanent: true },
      { source: '/en/umbrire/raffstore-venetian-blinds', destination: '/en/shading-systems/raffstore-venetian-blinds', permanent: true },
      { source: '/de/umbrire/raffstore-aussenjalousien', destination: '/de/beschattungssysteme/raffstore-aussenjalousien', permanent: true },
      { source: '/fr/umbrire/stores-venitiens-raffstore', destination: '/fr/systemes-occultation/stores-venitiens-raffstore', permanent: true },
      { source: '/es/umbrire/persianas-venecianas-raffstore', destination: '/es/sistemas-sombreado/persianas-venecianas-raffstore', permanent: true },
      { source: '/it/umbrire/veneziane-raffstore', destination: '/it/sistemi-oscuramento/veneziane-raffstore', permanent: true },
      { source: '/en/umbrire/zipscreen-exterior-blind', destination: '/en/shading-systems/zipscreen-exterior-blind', permanent: true },
      { source: '/de/umbrire/zipscreen-aussenrollo', destination: '/de/beschattungssysteme/zipscreen-aussenrollo', permanent: true },
      { source: '/fr/umbrire/zipscreen-store-exterieur', destination: '/fr/systemes-occultation/zipscreen-store-exterieur', permanent: true },
      { source: '/es/umbrire/zipscreen-toldo-exterior', destination: '/es/sistemas-sombreado/zipscreen-toldo-exterior', permanent: true },
      { source: '/it/umbrire/zipscreen-tenda-esterna', destination: '/it/sistemi-oscuramento/zipscreen-tenda-esterna', permanent: true },
      { source: '/en/umbrire/somfy-automatic-pergolas', destination: '/en/shading-systems/somfy-automatic-pergolas', permanent: true },
      { source: '/de/umbrire/somfy-automatische-pergolen', destination: '/de/beschattungssysteme/somfy-automatische-pergolen', permanent: true },
      { source: '/fr/umbrire/pergolas-automatiques-somfy', destination: '/fr/systemes-occultation/pergolas-automatiques-somfy', permanent: true },
      { source: '/es/umbrire/pergolas-automaticas-somfy', destination: '/es/sistemas-sombreado/pergolas-automaticas-somfy', permanent: true },
      { source: '/it/umbrire/pergole-automatiche-somfy', destination: '/it/sistemi-oscuramento/pergole-automatiche-somfy', permanent: true },
      // sisteme-nzeb
      { source: '/en/sisteme-nzeb/blaugelb-triotherm-plus-precasings', destination: '/en/nzeb-systems/blaugelb-triotherm-plus-precasings', permanent: true },
      { source: '/de/sisteme-nzeb/blaugelb-triotherm-plus-vorfenster', destination: '/de/nzeb-systeme/blaugelb-triotherm-plus-vorfenster', permanent: true },
      { source: '/fr/sisteme-nzeb/precadres-blaugelb-triotherm-plus', destination: '/fr/systemes-nzeb/precadres-blaugelb-triotherm-plus', permanent: true },
      { source: '/es/sisteme-nzeb/premarcos-blaugelb-triotherm-plus', destination: '/es/sistemas-nzeb/premarcos-blaugelb-triotherm-plus', permanent: true },
      { source: '/it/sisteme-nzeb/pre-telai-blaugelb-triotherm-plus', destination: '/it/sistemi-nzeb/pre-telai-blaugelb-triotherm-plus', permanent: true },
      { source: '/en/sisteme-nzeb/pre-compressed-butyl-sealing-tape', destination: '/en/nzeb-systems/pre-compressed-butyl-sealing-tape', permanent: true },
      { source: '/de/sisteme-nzeb/vorkomprimiertes-butyl-dichtband', destination: '/de/nzeb-systeme/vorkomprimiertes-butyl-dichtband', permanent: true },
      { source: '/fr/sisteme-nzeb/bande-precomprimee-butyle', destination: '/fr/systemes-nzeb/bande-precomprimee-butyle', permanent: true },
      { source: '/es/sisteme-nzeb/cinta-precomprimida-butilica', destination: '/es/sistemas-nzeb/cinta-precomprimida-butilica', permanent: true },
      { source: '/it/sisteme-nzeb/nastro-precompresso-butilico', destination: '/it/sistemi-nzeb/nastro-precompresso-butilico', permanent: true },
      { source: '/en/sisteme-nzeb/interior-vapour-barrier-sealing-tape', destination: '/en/nzeb-systems/interior-vapour-barrier-sealing-tape', permanent: true },
      { source: '/de/sisteme-nzeb/innen-dampfsperrband', destination: '/de/nzeb-systeme/innen-dampfsperrband', permanent: true },
      { source: '/fr/sisteme-nzeb/ruban-etancheite-pare-vapeur-interieur', destination: '/fr/systemes-nzeb/ruban-etancheite-pare-vapeur-interieur', permanent: true },
      { source: '/es/sisteme-nzeb/banda-sellado-barrera-vapor-interior', destination: '/es/sistemas-nzeb/banda-sellado-barrera-vapor-interior', permanent: true },
      { source: '/it/sisteme-nzeb/nastro-tenuta-barriera-vapore-interno', destination: '/it/sistemi-nzeb/nastro-tenuta-barriera-vapore-interno', permanent: true },
      { source: '/en/sisteme-nzeb/warm-edge-thermo-spacer-insulating-glass', destination: '/en/nzeb-systems/warm-edge-thermo-spacer-insulating-glass', permanent: true },
      { source: '/de/sisteme-nzeb/warm-edge-thermo-abstandhalter-isolierglas', destination: '/de/nzeb-systeme/warm-edge-thermo-abstandhalter-isolierglas', permanent: true },
      { source: '/fr/sisteme-nzeb/espaceur-warm-edge-thermo-vitrage', destination: '/fr/systemes-nzeb/espaceur-warm-edge-thermo-vitrage', permanent: true },
      { source: '/es/sisteme-nzeb/separador-warm-edge-thermo-vidrio-aislante', destination: '/es/sistemas-nzeb/separador-warm-edge-thermo-vidrio-aislante', permanent: true },
      { source: '/it/sisteme-nzeb/distanziale-warm-edge-thermo-vetro-isolante', destination: '/it/sistemi-nzeb/distanziale-warm-edge-thermo-vetro-isolante', permanent: true },
      { source: '/en/sisteme-nzeb/saint-gobain-sgg-thermal-insulating-glass', destination: '/en/nzeb-systems/saint-gobain-sgg-thermal-insulating-glass', permanent: true },
      { source: '/de/sisteme-nzeb/saint-gobain-sgg-waermeschutzisolierglas', destination: '/de/nzeb-systeme/saint-gobain-sgg-waermeschutzisolierglas', permanent: true },
      { source: '/fr/sisteme-nzeb/vitrage-isolant-saint-gobain-sgg', destination: '/fr/systemes-nzeb/vitrage-isolant-saint-gobain-sgg', permanent: true },
      { source: '/es/sisteme-nzeb/vidrio-aislante-saint-gobain-sgg', destination: '/es/sistemas-nzeb/vidrio-aislante-saint-gobain-sgg', permanent: true },
      { source: '/it/sisteme-nzeb/vetro-termoisolante-saint-gobain-sgg', destination: '/it/sistemi-nzeb/vetro-termoisolante-saint-gobain-sgg', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
      {
        // Cache agresiv pe assets statice
        source: '/(.*)\\.(avif|webp|jpg|jpeg|png|ico|svg|woff2|woff)',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
    ];
  },
};

module.exports = withNextIntl(nextConfig);
