const createNextIntlPlugin = require('next-intl/plugin');
const withNextIntl = createNextIntlPlugin();

const nextConfig = {
  compress: true,
  experimental: {
    serverActions: { bodySizeLimit: '20mb' },
    optimizePackageImports: ['next-intl'],
  },
  // images: config eliminat (v188) — next/image nu e folosit nicăieri în proiect (cotă Vercel epuizată, decizie definitivă)
  async redirects() {
    return [
      // === v188: eliminare duplicate content /ghid → /ghid-complet (8 pagini, audit Mai 2026) ===
      { source: '/ro/tamplarie-pvc/ghid',          destination: '/ro/tamplarie-pvc/ghid-complet',                    permanent: true },
      { source: '/en/pvc-windows/ghid',            destination: '/en/pvc-windows/complete-guide',                    permanent: true },
      { source: '/de/kunststofffenster-pvc/ghid',  destination: '/de/kunststofffenster-pvc/kompletter-ratgeber',     permanent: true },
      { source: '/fr/menuiserie-pvc/ghid',         destination: '/fr/menuiserie-pvc/guide-complet',                  permanent: true },
      { source: '/es/carpinteria-pvc/ghid',        destination: '/es/carpinteria-pvc/guia-completa',                 permanent: true },
      { source: '/it/infissi-pvc/ghid',            destination: '/it/infissi-pvc/guida-completa',                    permanent: true },

      { source: '/ro/tamplarie-aluminiu/ghid',     destination: '/ro/tamplarie-aluminiu/ghid-complet',               permanent: true },
      { source: '/en/aluminium-windows/ghid',      destination: '/en/aluminium-windows/complete-guide',              permanent: true },
      { source: '/de/aluminiumfenster/ghid',       destination: '/de/aluminiumfenster/kompletter-ratgeber',          permanent: true },
      { source: '/fr/menuiserie-aluminium/ghid',   destination: '/fr/menuiserie-aluminium/guide-complet',            permanent: true },
      { source: '/es/carpinteria-aluminio/ghid',   destination: '/es/carpinteria-aluminio/guia-completa',            permanent: true },
      { source: '/it/infissi-alluminio/ghid',      destination: '/it/infissi-alluminio/guida-completa',              permanent: true },

      { source: '/ro/umbrire/ghid',                destination: '/ro/umbrire/ghid-complet-sisteme-umbrire',          permanent: true },
      { source: '/en/shading-systems/ghid',        destination: '/en/shading-systems/complete-guide',                permanent: true },
      { source: '/de/beschattungssysteme/ghid',    destination: '/de/beschattungssysteme/kompletter-ratgeber',       permanent: true },
      { source: '/fr/systemes-occultation/ghid',   destination: '/fr/systemes-occultation/guide-complet',            permanent: true },
      { source: '/es/sistemas-sombreado/ghid',     destination: '/es/sistemas-sombreado/guia-completa',              permanent: true },
      { source: '/it/sistemi-oscuramento/ghid',    destination: '/it/sistemi-oscuramento/guida-completa',            permanent: true },

      { source: '/ro/sisteme-nzeb/ghid',           destination: '/ro/sisteme-nzeb/ghid-complet-nzeb',                permanent: true },
      { source: '/en/nzeb-systems/ghid',           destination: '/en/nzeb-systems/complete-guide',                   permanent: true },
      { source: '/de/nzeb-systeme/ghid',           destination: '/de/nzeb-systeme/kompletter-ratgeber',              permanent: true },
      { source: '/fr/systemes-nzeb/ghid',          destination: '/fr/systemes-nzeb/guide-complet',                   permanent: true },
      { source: '/es/sistemas-nzeb/ghid',          destination: '/es/sistemas-nzeb/guia-completa',                   permanent: true },
      { source: '/it/sistemi-nzeb/ghid',           destination: '/it/sistemi-nzeb/guida-completa',                   permanent: true },
      // === v188: pagina Termeni și Condiții ștearsă definitiv (era promisă ștearsă în v181, dar fișierul rămăsese pe disk) ===
      { source: '/ro/termeni-si-conditii',         destination: '/ro/despre',                                        permanent: true },

      { source: '/despre',         destination: '/ro/despre',         permanent: true },
      { source: '/about',          destination: '/en/about',          permanent: true },
      { source: '/ueber-uns',      destination: '/de/ueber-uns',      permanent: true },
      { source: '/a-propos',       destination: '/fr/a-propos',       permanent: true },
      { source: '/sobre-nosotros', destination: '/es/sobre-nosotros', permanent: true },
      { source: '/chi-siamo',      destination: '/it/chi-siamo',      permanent: true },
      { source: '/gdpr',             destination: '/ro/gdpr',           permanent: true },
      { source: '/privacy-policy',   destination: '/en/privacy-policy', permanent: true },
      { source: '/datenschutz',      destination: '/de/datenschutz',    permanent: true },
      { source: '/contact',          destination: '/ro/contact',        permanent: true },
      { source: '/blog',             destination: '/ro/blog',           permanent: true },
      { source: '/servicii',         destination: '/ro/servicii',       permanent: true },
      { source: '/accesorii',        destination: '/ro/accesorii',      permanent: true },
      // Fix dublu slash URLs (crawled de Google dar neindexate)
      { source: '/en//tamplarie-pvc',  destination: '/en/pvc-windows',            permanent: true },
      { source: '/en//pvc-windows',    destination: '/en/pvc-windows',            permanent: true },
      // === Redirecturi folder parinte gresit → corect (95 URL-uri neindexate) ===
      // accesorii
      { source: '/en/accesorii/pvc-renovation-frame', destination: '/en/accessories/pvc-renovation-frame', permanent: true },
      { source: '/de/accesorii/pvc-renovierungsrahmen', destination: '/de/zubehoer/pvc-renovierungsrahmen', permanent: true },
      { source: '/fr/accesorii/cadre-renovation-pvc', destination: '/fr/accessoires/cadre-renovation-pvc', permanent: true },
      { source: '/es/accesorii/marco-renovacion-pvc', destination: '/es/accesorios/marco-renovacion-pvc', permanent: true },
      { source: '/it/accesorii/telaio-ristrutturazione-pvc', destination: '/it/accessori/telaio-ristrutturazione-pvc', permanent: true },
      { source: '/en/accesorii/interior-pvc-windowsills-exterior-aluminium-sills', destination: '/en/accessories/interior-pvc-windowsills-exterior-aluminium-sills', permanent: true },
      { source: '/de/accesorii/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', destination: '/de/zubehoer/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', permanent: true },
      { source: '/fr/accesorii/appuis-fenetre-interieurs-pvc-exterieurs-aluminium', destination: '/fr/accessoires/appuis-fenetre-interieurs-pvc-exterieurs-aluminium', permanent: true },
      { source: '/es/accesorii/alfeizares-interiores-pvc-exteriores-aluminio', destination: '/es/accesorios/alfeizares-interiores-pvc-exteriores-aluminio', permanent: true },
      { source: '/it/accesorii/davanzali-interni-pvc-esterni-alluminio', destination: '/it/accessori/davanzali-interni-pvc-esterni-alluminio', permanent: true },
      { source: '/en/accesorii/aereco-hygro-adjustable-ventilation-grille', destination: '/en/accessories/aereco-hygro-adjustable-ventilation-grille', permanent: true },
      { source: '/de/accesorii/aereco-hygroregelbare-lueftungsgitter', destination: '/de/zubehoer/aereco-hygroregelbare-lueftungsgitter', permanent: true },
      { source: '/fr/accesorii/grille-hygroreglable-aereco-ventilation', destination: '/fr/accessoires/grille-hygroreglable-aereco-ventilation', permanent: true },
      { source: '/es/accesorii/rejilla-higrorreglable-aereco-ventilacion', destination: '/es/accesorios/rejilla-higrorreglable-aereco-ventilacion', permanent: true },
      { source: '/it/accesorii/griglia-igroregolab-aereco-ventilazione', destination: '/it/accessori/griglia-igroregolab-aereco-ventilazione', permanent: true },
      { source: '/en/accesorii/somfy-automation-shutters-pergolas', destination: '/en/accessories/somfy-automation-shutters-pergolas', permanent: true },
      { source: '/de/accesorii/somfy-automatisierung-rolllaeden-pergolen', destination: '/de/zubehoer/somfy-automatisierung-rolllaeden-pergolen', permanent: true },
      { source: '/fr/accesorii/automatisation-somfy-volets-pergolas', destination: '/fr/accessoires/automatisation-somfy-volets-pergolas', permanent: true },
      { source: '/es/accesorii/automatizacion-somfy-persianas-pergolas', destination: '/es/accesorios/automatizacion-somfy-persianas-pergolas', permanent: true },
      { source: '/it/accesorii/automazione-somfy-tapparelle-pergole', destination: '/it/accessori/automazione-somfy-tapparelle-pergole', permanent: true },
      // produse-aluminiu
      { source: '/en/produse-aluminiu/alumil-s77-supreme-aluminium-system', destination: '/en/products-alu/alumil-s77-supreme-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s77-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-s77-supreme-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s77-supreme', destination: '/fr/produits-alu/systeme-aluminium-alumil-s77-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s77-supreme', destination: '/es/productos-alu/sistema-aluminio-alumil-s77-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s77-supreme', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s77-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s67-smartia-aluminium-system', destination: '/en/products-alu/alumil-s67-smartia-aluminium-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s67-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-s67-smartia-aluminiumsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s67-smartia', destination: '/fr/produits-alu/systeme-aluminium-alumil-s67-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s67-smartia', destination: '/es/productos-alu/sistema-aluminio-alumil-s67-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s67-smartia', destination: '/it/prodotti-alu/sistema-alluminio-alumil-s67-smartia', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s700-supreme-aluminium-system', destination: '/en/products-alu/alumil-s700-supreme-lift-slide-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s700-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-s700-supreme-hebeschiebesystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s700-supreme', destination: '/fr/produits-alu/systeme-coulissant-alumil-s700-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s700-supreme', destination: '/es/productos-alu/sistema-corredera-alumil-s700-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s700-supreme', destination: '/it/prodotti-alu/sistema-scorrevole-alumil-s700-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-s350-smartia-aluminium-system', destination: '/en/products-alu/alumil-s350-smartia-lift-slide-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-s350-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-s350-smartia-hebeschiebesystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-s350-smartia', destination: '/fr/produits-alu/systeme-coulissant-alumil-s350-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-s350-smartia', destination: '/es/productos-alu/sistema-corredera-alumil-s350-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-s350-smartia', destination: '/it/prodotti-alu/sistema-scorrevole-alumil-s350-smartia', permanent: true },
      { source: '/en/produse-aluminiu/alumil-sf85-supreme-aluminium-system', destination: '/en/products-alu/alumil-sf85-supreme-folding-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-sf85-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-sf85-supreme-faltsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-sf85-supreme', destination: '/fr/produits-alu/systeme-pliant-alumil-sf85-supreme', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-sf85-supreme', destination: '/es/productos-alu/sistema-plegable-alumil-sf85-supreme', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-sf85-supreme', destination: '/it/prodotti-alu/sistema-pieghevole-alumil-sf85-supreme', permanent: true },
      { source: '/en/produse-aluminiu/alumil-m19800-smartia-aluminium-system', destination: '/en/products-alu/alumil-m19800-smartia-folding-system', permanent: true },
      { source: '/de/produse-aluminiu/alumil-m19800-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-m19800-smartia-faltsystem', permanent: true },
      { source: '/fr/produse-aluminiu/systeme-aluminium-alumil-m19800-smartia', destination: '/fr/produits-alu/systeme-pliant-alumil-m19800-smartia', permanent: true },
      { source: '/es/produse-aluminiu/sistema-aluminio-alumil-m19800-smartia', destination: '/es/productos-alu/sistema-plegable-alumil-m19800-smartia', permanent: true },
      { source: '/it/produse-aluminiu/sistema-alluminio-alumil-m19800-smartia', destination: '/it/prodotti-alu/sistema-pieghevole-alumil-m19800-smartia', permanent: true },
      // umbrire
      { source: '/en/umbrire/aluminium-external-roller-shutters', destination: '/en/shading-systems/aluminium-external-roller-shutters', permanent: true },
      { source: '/de/umbrire/aluminium-aussenrollladen', destination: '/de/beschattungssysteme/aluminium-aussenrollladen', permanent: true },
      { source: '/fr/umbrire/volets-roulants-aluminium-exterieurs', destination: '/fr/systemes-occultation/volets-roulants-aluminium-exterieurs', permanent: true },
      { source: '/es/umbrire/persianas-exteriores-aluminio', destination: '/es/sistemas-sombreado/persianas-exteriores-aluminio', permanent: true },
      { source: '/it/umbrire/tapparelle-esterne-alluminio', destination: '/it/sistemi-oscuramento/tapparelle-esterne-alluminio', permanent: true },
      { source: '/en/umbrire/raffstore-venetian-blinds', destination: '/en/shading-systems/raffstore-venetian-blinds', permanent: true },
      { source: '/de/umbrire/raffstore-aussenjalousien', destination: '/de/beschattungssysteme/raffstore-aussenjalousien', permanent: true },
      { source: '/fr/umbrire/stores-venitiens-raffstore', destination: '/fr/systemes-occultation/stores-venitiens-raffstore', permanent: true },
      { source: '/es/umbrire/persianas-venecianas-raffstore', destination: '/es/sistemas-sombreado/persianas-venecianas-raffstore', permanent: true },
      { source: '/it/umbrire/veneziane-raffstore', destination: '/it/sistemi-oscuramento/veneziane-raffstore', permanent: true },
      { source: '/en/umbrire/zipscreen-exterior-blind', destination: '/en/shading-systems/zipscreen-exterior-blind', permanent: true },
      { source: '/de/umbrire/zipscreen-aussenrollo', destination: '/de/beschattungssysteme/zipscreen-aussenrollo', permanent: true },
      { source: '/fr/umbrire/zipscreen-store-exterieur', destination: '/fr/systemes-occultation/zipscreen-store-exterieur', permanent: true },
      { source: '/es/umbrire/zipscreen-toldo-exterior', destination: '/es/sistemas-sombreado/zipscreen-toldo-exterior', permanent: true },
      { source: '/it/umbrire/zipscreen-tenda-esterna', destination: '/it/sistemi-oscuramento/zipscreen-tenda-esterna', permanent: true },
      { source: '/en/umbrire/somfy-automatic-pergolas', destination: '/en/shading-systems/somfy-automatic-pergolas', permanent: true },
      { source: '/de/umbrire/somfy-automatische-pergolen', destination: '/de/beschattungssysteme/somfy-automatische-pergolen', permanent: true },
      { source: '/fr/umbrire/pergolas-automatiques-somfy', destination: '/fr/systemes-occultation/pergolas-automatiques-somfy', permanent: true },
      { source: '/es/umbrire/pergolas-automaticas-somfy', destination: '/es/sistemas-sombreado/pergolas-automaticas-somfy', permanent: true },
      { source: '/it/umbrire/pergole-automatiche-somfy', destination: '/it/sistemi-oscuramento/pergole-automatiche-somfy', permanent: true },
      // sisteme-nzeb
      { source: '/en/sisteme-nzeb/blaugelb-triotherm-plus-precasings', destination: '/en/nzeb-systems/blaugelb-triotherm-plus-precasings', permanent: true },
      { source: '/de/sisteme-nzeb/blaugelb-triotherm-plus-vorfenster', destination: '/de/nzeb-systeme/blaugelb-triotherm-plus-vorfenster', permanent: true },
      { source: '/fr/sisteme-nzeb/precadres-blaugelb-triotherm-plus', destination: '/fr/systemes-nzeb/precadres-blaugelb-triotherm-plus', permanent: true },
      { source: '/es/sisteme-nzeb/premarcos-blaugelb-triotherm-plus', destination: '/es/sistemas-nzeb/premarcos-blaugelb-triotherm-plus', permanent: true },
      { source: '/it/sisteme-nzeb/pre-telai-blaugelb-triotherm-plus', destination: '/it/sistemi-nzeb/pre-telai-blaugelb-triotherm-plus', permanent: true },
      { source: '/en/sisteme-nzeb/pre-compressed-butyl-sealing-tape', destination: '/en/nzeb-systems/pre-compressed-butyl-sealing-tape', permanent: true },
      { source: '/de/sisteme-nzeb/vorkomprimiertes-butyl-dichtband', destination: '/de/nzeb-systeme/vorkomprimiertes-butyl-dichtband', permanent: true },
      { source: '/fr/sisteme-nzeb/bande-precomprimee-butyle', destination: '/fr/systemes-nzeb/bande-precomprimee-butyle', permanent: true },
      { source: '/es/sisteme-nzeb/cinta-precomprimida-butilica', destination: '/es/sistemas-nzeb/cinta-precomprimida-butilica', permanent: true },
      { source: '/it/sisteme-nzeb/nastro-precompresso-butilico', destination: '/it/sistemi-nzeb/nastro-precompresso-butilico', permanent: true },
      { source: '/en/sisteme-nzeb/interior-vapour-barrier-sealing-tape', destination: '/en/nzeb-systems/interior-vapour-barrier-sealing-tape', permanent: true },
      { source: '/de/sisteme-nzeb/innen-dampfsperrband', destination: '/de/nzeb-systeme/innen-dampfsperrband', permanent: true },
      { source: '/fr/sisteme-nzeb/ruban-etancheite-pare-vapeur-interieur', destination: '/fr/systemes-nzeb/ruban-etancheite-pare-vapeur-interieur', permanent: true },
      { source: '/es/sisteme-nzeb/banda-sellado-barrera-vapor-interior', destination: '/es/sistemas-nzeb/banda-sellado-barrera-vapor-interior', permanent: true },
      { source: '/it/sisteme-nzeb/nastro-tenuta-barriera-vapore-interno', destination: '/it/sistemi-nzeb/nastro-tenuta-barriera-vapore-interno', permanent: true },
      { source: '/en/sisteme-nzeb/warm-edge-thermo-spacer-insulating-glass', destination: '/en/nzeb-systems/warm-edge-thermo-spacer-insulating-glass', permanent: true },
      { source: '/de/sisteme-nzeb/warm-edge-thermo-abstandhalter-isolierglas', destination: '/de/nzeb-systeme/warm-edge-thermo-abstandhalter-isolierglas', permanent: true },
      { source: '/fr/sisteme-nzeb/espaceur-warm-edge-thermo-vitrage', destination: '/fr/systemes-nzeb/espaceur-warm-edge-thermo-vitrage', permanent: true },
      { source: '/es/sisteme-nzeb/separador-warm-edge-thermo-vidrio-aislante', destination: '/es/sistemas-nzeb/separador-warm-edge-thermo-vidrio-aislante', permanent: true },
      { source: '/it/sisteme-nzeb/distanziale-warm-edge-thermo-vetro-isolante', destination: '/it/sistemi-nzeb/distanziale-warm-edge-thermo-vetro-isolante', permanent: true },
      { source: '/en/sisteme-nzeb/saint-gobain-sgg-thermal-insulating-glass', destination: '/en/nzeb-systems/saint-gobain-sgg-thermal-insulating-glass', permanent: true },
      { source: '/de/sisteme-nzeb/saint-gobain-sgg-waermeschutzisolierglas', destination: '/de/nzeb-systeme/saint-gobain-sgg-waermeschutzisolierglas', permanent: true },
      { source: '/fr/sisteme-nzeb/vitrage-isolant-saint-gobain-sgg', destination: '/fr/systemes-nzeb/vitrage-isolant-saint-gobain-sgg', permanent: true },
      { source: '/es/sisteme-nzeb/vidrio-aislante-saint-gobain-sgg', destination: '/es/sistemas-nzeb/vidrio-aislante-saint-gobain-sgg', permanent: true },
      { source: '/it/sisteme-nzeb/vetro-termoisolante-saint-gobain-sgg', destination: '/it/sistemi-nzeb/vetro-termoisolante-saint-gobain-sgg', permanent: true },
      // === v196: articol 'inchidere balcon/terasa' sters (5 limbi) -> pillar aluminiu ===
      { source: '/ro/blog/inchidere-balcon-terasa-tamplarie-aluminiu-bucuresti-2026', destination: '/ro/tamplarie-aluminiu', permanent: true },
      { source: '/en/blog/balcony-terrace-enclosure-aluminium-windows-bucharest-2026', destination: '/en/aluminium-windows', permanent: true },
      { source: '/de/blog/balkon-terrasse-verglasung-aluminium-bukarest-2026', destination: '/de/aluminiumfenster', permanent: true },
      { source: '/fr/blog/fermeture-balcon-terrasse-menuiserie-aluminium-bucarest-2026', destination: '/fr/menuiserie-aluminium', permanent: true },
      { source: '/es/blog/cierre-balcon-terraza-carpinteria-aluminio-bucarest-2026', destination: '/es/carpinteria-aluminio', permanent: true },
      { source: '/it/blog/chiusura-balcone-terrazza-infissi-alluminio-bucarest-2026', destination: '/it/infissi-alluminio', permanent: true },
      // === v196: fix 404-uri indexare (slug-uri vechi gresite) ===
      { source: '/it/produse/profilo-pvc-bluevolution-92-flex', destination: '/it/prodotti/profilo-pvc-bluevolution-92-flex', permanent: true },
      { source: '/de/produse/greenevolution-76-md-flex-pvc-profil', destination: '/de/produkte/greenevolution-76-md-flex-pvc-profil', permanent: true },
      { source: '/de/produse/greenevolution-76-md-round-pvc-profil', destination: '/de/produkte/greenevolution-76-md-round-pvc-profil', permanent: true },
      { source: '/es/banda-sellado-barrera-vapor-interior', destination: '/es/sistemas-nzeb/banda-sellado-barrera-vapor-interior', permanent: true },
      { source: '/home', destination: '/ro', permanent: true },
      { source: '/de/produse/bluevolution-92-flex-pvc-profil', destination: '/de/produkte/bluevolution-92-flex-pvc-profil', permanent: true },
      { source: '/it/produse/profilo-pvc-greenevolution-76-md-flex', destination: '/it/prodotti/profilo-pvc-greenevolution-76-md-flex', permanent: true },
      { source: '/en/produse/bluevolution-92-flex-pvc-profile', destination: '/en/products/bluevolution-92-flex-pvc-profile', permanent: true },
      { source: '/de/produse/bluevolution-92-alu-pvc-profil', destination: '/de/produkte/bluevolution-92-alu-pvc-profil', permanent: true },
      { source: '/de/produse/bluevolution-92-round-pvc-profil', destination: '/de/produkte/bluevolution-92-round-pvc-profil', permanent: true },
      { source: '/de/produse/greenevolution-76-ad-flex-pvc-profil', destination: '/de/produkte/greenevolution-76-ad-flex-pvc-profil', permanent: true },
      { source: '/en/produse/greenevolution-76-ad-flex-pvc-profile', destination: '/en/products/greenevolution-76-ad-flex-pvc-profile', permanent: true },
      { source: '/en/produse/greenevolution-76-md-flex-pvc-profile', destination: '/en/products/greenevolution-76-md-flex-pvc-profile', permanent: true },
      { source: '/en/produse/greenevolution-76-md-round-pvc-profile', destination: '/en/products/greenevolution-76-md-round-pvc-profile', permanent: true },
      { source: '/es/produse/perfil-pvc-bluevolution-92-alu', destination: '/es/productos/perfil-pvc-bluevolution-92-alu', permanent: true },
      { source: '/es/produse/perfil-pvc-bluevolution-92-round', destination: '/es/productos/perfil-pvc-bluevolution-92-round', permanent: true },
      { source: '/es/produse/perfil-pvc-greenevolution-76-ad-flex', destination: '/es/productos/perfil-pvc-greenevolution-76-ad-flex', permanent: true },
      { source: '/es/produse/perfil-pvc-greenevolution-76-md-round', destination: '/es/productos/perfil-pvc-greenevolution-76-md-round', permanent: true },
      { source: '/fr/produse/profil-pvc-bluevolution-92-alu', destination: '/fr/produits/profil-pvc-bluevolution-92-alu', permanent: true },
      { source: '/fr/produse/profil-pvc-bluevolution-92-flex', destination: '/fr/produits/profil-pvc-bluevolution-92-flex', permanent: true },
      { source: '/fr/produse/profil-pvc-bluevolution-92-round', destination: '/fr/produits/profil-pvc-bluevolution-92-round', permanent: true },
      { source: '/fr/produse/profil-pvc-greenevolution-76-ad-flex', destination: '/fr/produits/profil-pvc-greenevolution-76-ad-flex', permanent: true },
      { source: '/fr/produse/profil-pvc-greenevolution-76-md-flex', destination: '/fr/produits/profil-pvc-greenevolution-76-md-flex', permanent: true },
      { source: '/fr/produse/profil-pvc-greenevolution-76-md-round', destination: '/fr/produits/profil-pvc-greenevolution-76-md-round', permanent: true },
      { source: '/it/produse/profilo-pvc-bluevolution-92-round', destination: '/it/prodotti/profilo-pvc-bluevolution-92-round', permanent: true },
      { source: '/it/produse/profilo-pvc-greenevolution-76-ad-flex', destination: '/it/prodotti/profilo-pvc-greenevolution-76-ad-flex', permanent: true },
      { source: '/it/produse/profilo-pvc-greenevolution-76-md-round', destination: '/it/prodotti/profilo-pvc-greenevolution-76-md-round', permanent: true },
      { source: '/fr/produits-alu/systeme-aluminium-alumil-m19800-smartia', destination: '/fr/produits-alu/systeme-pliant-alumil-m19800-smartia', permanent: true },
      { source: '/de/produkte-alu/alumil-s350-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-s350-smartia-hebeschiebesystem', permanent: true },
      { source: '/it/prodotti-alu/sistema-alluminio-alumil-s350-smartia', destination: '/it/prodotti-alu/sistema-scorrevole-alumil-s350-smartia', permanent: true },
      { source: '/fr/produits-alu/systeme-aluminium-alumil-s700-supreme', destination: '/fr/produits-alu/systeme-coulissant-alumil-s700-supreme', permanent: true },
      { source: '/it/prodotti-alu/sistema-alluminio-alumil-sf85-supreme', destination: '/it/prodotti-alu/sistema-pieghevole-alumil-sf85-supreme', permanent: true },
      { source: '/en/products-alu/alumil-m19800-smartia-aluminium-system', destination: '/en/products-alu/alumil-m19800-smartia-folding-system', permanent: true },
      { source: '/it/prodotti-alu/sistema-alluminio-alumil-s700-supreme', destination: '/it/prodotti-alu/sistema-scorrevole-alumil-s700-supreme', permanent: true },
      { source: '/es/productos-alu/sistema-aluminio-alumil-m19800-smartia', destination: '/es/productos-alu/sistema-plegable-alumil-m19800-smartia', permanent: true },
      { source: '/fr/produits-alu/systeme-aluminium-alumil-s350-smartia', destination: '/fr/produits-alu/systeme-coulissant-alumil-s350-smartia', permanent: true },
      { source: '/es/productos-alu/sistema-aluminio-alumil-s700-supreme', destination: '/es/productos-alu/sistema-corredera-alumil-s700-supreme', permanent: true },
      { source: '/de/produkte-alu/alumil-s700-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-s700-supreme-hebeschiebesystem', permanent: true },
      { source: '/es/productos-alu/sistema-aluminio-alumil-sf85-supreme', destination: '/es/productos-alu/sistema-plegable-alumil-sf85-supreme', permanent: true },
      { source: '/es/productos-alu/sistema-aluminio-alumil-s350-smartia', destination: '/es/productos-alu/sistema-corredera-alumil-s350-smartia', permanent: true },
      { source: '/de/produkte-alu/alumil-m19800-smartia-aluminiumsystem', destination: '/de/produkte-alu/alumil-m19800-smartia-faltsystem', permanent: true },
      { source: '/de/produkte-alu/alumil-sf85-supreme-aluminiumsystem', destination: '/de/produkte-alu/alumil-sf85-supreme-faltsystem', permanent: true },
      { source: '/en/products-alu/alumil-s350-smartia-aluminium-system', destination: '/en/products-alu/alumil-s350-smartia-lift-slide-system', permanent: true },
      { source: '/en/products-alu/alumil-s700-supreme-aluminium-system', destination: '/en/products-alu/alumil-s700-supreme-lift-slide-system', permanent: true },
      { source: '/en/products-alu/alumil-sf85-supreme-aluminium-system', destination: '/en/products-alu/alumil-sf85-supreme-folding-system', permanent: true },
      { source: '/fr/produits-alu/systeme-aluminium-alumil-sf85-supreme', destination: '/fr/produits-alu/systeme-pliant-alumil-sf85-supreme', permanent: true },
      { source: '/it/prodotti-alu/sistema-alluminio-alumil-m19800-smartia', destination: '/it/prodotti-alu/sistema-pieghevole-alumil-m19800-smartia', permanent: true },
      { source: '/it/blog/rulouri-zipscreen-blackout-sau-transparent-cum-alegi', destination: '/it/blog/tende-zipscreen-oscuranti-o-trasparenti-come-scegliere', permanent: true },
      { source: '/blog/esportazione-serramenti-romania-germania', destination: '/ro/blog/export-tamplarie-germania', permanent: true },
      { source: '/de/blog/usi-intrare-antiefractie-comanda-tactica-amprenta-digitala-aluminiu', destination: '/de/blog/einbruchsichere-eingangstuer-fingerabdruck-touchbedienung-aluminium', permanent: true },
      { source: '/blog/come-scegliere-finestre-efficienti-energeticamente-bucarest-nzeb-2026', destination: '/ro/blog/cum-aleg-ferestre-eficiente-energetic-bucuresti-ghid-nzeb-2026', permanent: true },
      { source: '/blog/porta-ingresso-antieffrazione-comando-tattile-impronta-digitale-alluminio', destination: '/ro/blog/usi-intrare-antiefractie-comanda-tactica-amprenta-digitala-aluminiu', permanent: true },
      { source: '/blog/prezzi-finestre-salamander-bucarest-2026', destination: '/ro/blog/preturi-ferestre-salamander-bucuresti-2026', permanent: true },
      { source: '/blog/unde-cumpar-jaluzele-exterioare-bucuresti', destination: '/ro/blog/unde-cumpar-jaluzele-exterioare-bucuresti', permanent: true },
      { source: '/blog/jaluzele-raffstore-vs-rulouri-aluminiu', destination: '/ro/blog/jaluzele-raffstore-vs-rulouri-aluminiu', permanent: true },
      { source: '/blog/somfy-automatisation-pergola-store', destination: '/ro/blog/somfy-automatizare-pergole-copertine', permanent: true },
      { source: '/en/blog/ventana-pvc-oscilobatiente-doble-salamander', destination: '/en/blog/tilt-turn-double-pvc-windows-salamander', permanent: true },
      { source: '/de/blog/tamplarie-aluminiu-bariera-termica-ghid-complet', destination: '/de/blog/aluminiumfenster-waermedaemmung-komplett-leitfaden', permanent: true },
      { source: '/es/blog/tamplarie-pvc-osciloculisanta-dubla-salamander', destination: '/es/blog/ventana-pvc-oscilobatiente-doble-salamander', permanent: true },
      { source: '/de/blog/puerta-corredera-pvc-salamander-evolutiondrive-plus-mosquitera-plise', destination: '/de/blog/salamander-evolutiondrive-plus-schiebetuer-plissee', permanent: true },
      { source: '/en/blog/parete-cortina-facciata-vetro-guida-completa', destination: '/en/blog/curtain-wall-glass-facades-complete-guide', permanent: true },
      { source: '/de/blog/montaj-tamplarie-salamander-evolutiondrive-plus-culisanta-alumil-m19800-armonice', destination: '/de/blog/montage-salamander-evolutiondrive-plus-schiebetuer-alumil-m19800-falttuer', permanent: true },
      { source: '/de/blog/tamplarie-pvc-osciloculisanta-dubla-salamander', destination: '/de/blog/pvc-fenster-dreh-kipp-salamander', permanent: true },
      { source: '/de/blog/zipscreen-umbrire-terasa-ghid-complet', destination: '/de/blog/zipscreen-terrassenbeschattung-komplettleitfaden', permanent: true },
      { source: '/en/accesorii/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', destination: '/en/accessories/interior-pvc-windowsills-exterior-aluminium-sills', permanent: true },
      { source: '/es/accesorii/innenfensterbaenke-pvc-aussenfensterbaenke-aluminium', destination: '/es/accesorios/alfeizares-interiores-pvc-exteriores-aluminio', permanent: true },
      { source: '/de/accesorii/rejilla-higrorreglable-aereco-ventilacion', destination: '/de/zubehoer/aereco-hygroregelbare-lueftungsgitter', permanent: true },
      { source: '/de/produse/profilo-pvc-greenevolution-76-md-flex', destination: '/de/produkte/greenevolution-76-md-flex-pvc-profil', permanent: true },
      { source: '/es/sisteme-nzeb/distanziale-warm-edge-thermo-vetro-isolante', destination: '/es/sistemas-nzeb/separador-warm-edge-thermo-vidrio-aislante', permanent: true },
      { source: '/de/produse-aluminiu/systeme-aluminium-alumil-s77-supreme', destination: '/de/produkte-alu/alumil-s77-supreme-aluminiumsystem', permanent: true },
      { source: '/sisteme-nzeb', destination: '/ro/sisteme-nzeb', permanent: true },
      { source: '/produse-aluminiu', destination: '/ro/tamplarie-aluminiu', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
      {
        // Cache agresiv pe assets statice
        source: '/(.*)\\.(avif|webp|jpg|jpeg|png|ico|svg|woff2|woff)',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
    ];
  },
};

module.exports = withNextIntl(nextConfig);
