const BASE = 'https://www.neofort-biz.ro';
const SLUGS = {
  ro: 'termeni-si-conditii',
  en: 'terms-and-conditions',
  de: 'allgemeine-geschaeftsbedingungen',
  fr: 'conditions-generales',
  es: 'terminos-y-condiciones',
  it: 'termini-e-condizioni',
};

const UI = {
  ro: {
    label: 'Legal',
    h1: 'Termeni și Condiții Generale',
    sub: 'Condiții generale de vânzare, livrare, montaj și garanție — NEOFORT BIZ SRL (CUI RO30324211). Ultima actualizare: Mai 2026.',
    title_meta: 'Termeni și Condiții · Neofort BIZ',
    desc_meta: 'Termeni și condiții generale Neofort BIZ SRL — comandă fermă, livrare, montaj, garanție comercială conform OUG 140/2021 pentru tâmplărie PVC Salamander și aluminiu Alumil.',
    sections: [
      { h: '1. Informații societate', p: 'NEOFORT BIZ SRL, înregistrată la Registrul Comerțului sub nr. J40/6928/2012, CUI RO30324211, EUID ROONRC.J40/6928/2012, sediu: Str. Theodor Aman Pictor nr.11, Sector 1, București 010776, România. E-mail: oferte@neofort-biz.ro · Telefon: +40 752 443 435 · Program: Luni–Vineri 09:00–18:00.' },
      { h: '2. Natura produselor — Comandă fermă pe specificații individuale', p: 'Toate produsele furnizate de NEOFORT BIZ SRL — tâmplărie PVC Salamander, tâmplărie aluminiu Alumil, sisteme de umbrire (jaluzele Raffstore, rulouri exterioare), accesorii — sunt fabricate exclusiv la comanda fermă a clientului, pe dimensiunile, configurațiile și specificațiile tehnice individuale stabilite prin contract. Odată lansată comanda în producție, produsele nu pot fi anulate, modificate, returnate sau substituite. Nu există drept de retragere sau renunțare la comandă după confirmarea contractului și lansarea în producție, în conformitate cu art. 16 lit. (c) din Directiva 2011/83/UE și OUG 34/2014 — excepție expresă pentru bunuri confecționate după specificațiile consumatorului sau personalizate în mod clar.' },
      { h: '3. Procesul de comandă și confirmarea contractuală', p: 'Comanda se inițiază prin formularul de contact de pe site, telefon sau e-mail. NEOFORT BIZ SRL transmite o ofertă de preț individualizată, valabilă 30 de zile de la emitere. Confirmarea comenzii de către client și plata avansului contractual constituie acceptarea irevocabilă a ofertei și declanșează procesul de producție. Termenul de livrare și montaj este de 10–21 de zile lucrătoare de la confirmarea plății avansului, în funcție de complexitatea comenzii.' },
      { h: '4. Prețuri, TVA și modalități de plată', p: 'Prețurile din ofertă sunt exprimate în Lei (RON) fără TVA. TVA 19% se adaugă conform legislației fiscale în vigoare. Plata se efectuează prin transfer bancar sau numerar la sediul companiei. Avans minim: 50% din valoarea contractului la confirmarea comenzii. Restul: la finalizarea montajului sau la livrare (pentru comenzi fără montaj). NEOFORT BIZ SRL își rezervă dreptul de a revizui prețurile în cazul fluctuațiilor de curs valutar mai mari de 5% față de data ofertei.' },
      { h: '5. Livrare și montaj profesional', p: 'Livrarea se face la adresa specificată de client în comanda confirmată. Montajul profesional se execută de echipele specializate NEOFORT BIZ SRL, conform standardului RAL, cu benzi precomprimate butilice și trei zone de etanșare (exterior, intermediar, interior). Clientul are obligația de a asigura accesul liber la locul de montaj și pregătirea golurilor conform specificațiilor tehnice comunicate de furnizor. Lucrările conexe (demolări, zidărie, finisaje) nu sunt incluse în prețul standard și se contractează separat. Recepția lucrării se finalizează prin semnarea Procesului Verbal de Recepție.' },
      { h: '6. Garanție comercială', p: 'NEOFORT BIZ SRL acordă garanție comercială în conformitate cu OUG nr. 140/2021 și standardele tehnice SR EN 12608, SR EN 12020-2, SR EN 1279, după cum urmează: (a) Profile PVC Salamander: 5 ani față de defecte de fabricație și material (stabilitate cromatică, rezistență la impact, integritate structurală); (b) Profile aluminiu Alumil: 5 ani față de defecte de fabricație (aderența stratului de vopsea, rezistență la coroziune, integritate profil); (c) Feronerie Roto/Winkhaus/GU: 2 ani față de defecte de funcționare a mecanismelor de închidere/deschidere, cu condiția efectuării mentenanței periodice; (d) Geam termoizolant: 5 ani față de defecte de etanșeitate (aburire între foi) și defecte optice conform SR EN 1279; (e) Montaj profesional (efectuat de NEOFORT BIZ SRL): 5 ani față de etanșeitatea perimetrală a tâmplăriei față de zidărie. Perioada de garanție curge de la data semnării Procesului Verbal de Recepție a lucrării sau de la data introducerii facturii fiscale în SPV.' },
      { h: '7. Evaluarea defectelor — Standarde tehnice aplicabile', p: 'Evaluarea oricărui defect reclamat se realizează strict conform normativelor tehnice în vigoare: (1) Inspecția vizuală se efectuează de la o distanță de minimum 3 metri, sub lumină naturală difuză, conform SR EN 1279-1:2018 — defectele invizibile de la această distanță sunt considerate conforme; (2) Abaterile dimensionale de până la ±2 mm și micile variații de nuanță între loturi de producție sunt admise și nu constituie lipsă de conformitate, conform SR EN 12608-1 și SR EN 12020-2; (3) Condensul pe fața interioară a geamului (spre cameră) nu reprezintă un defect de produs — este consecința umidității excesive și ventilației insuficiente a spațiului. Garanția acoperă exclusiv condensul apărut între foile pachetului de geam (defect de etanșeitate a sigiliului).' },
      { h: '8. Excluderi și anularea garanției', p: 'Garanția se anulează sau nu se aplică în următoarele situații: (a) Neprotejarea produselor în timpul lucrărilor de amenajare interioară — prezența urmelor de praf de construcții (glet, ciment, var, tencuială) pe feronerie sau profile anulează garanția pentru mecanismele de închidere; (b) Curățarea cu substanțe acide, abrazive, solvenți (acetonă, diluant) sau obiecte ascuțite; (c) Intervenții neautorizate — montarea de accesorii (rulouri, plase, glafuri) de către terți prin găurirea sau modificarea profilelor; (d) Forțarea mecanismelor — rotirea mânerului cu fereastra deschisă sau blocarea cu obiecte străine; (e) Nerespectarea mentenanței obligatorii — feroneria trebuie unsă cu ulei siliconic de minimum 2 ori pe an; (f) Neplata integrală a prețului contractual — orice restanță de plată suspendă garanția până la achitarea integrală.' },
      { h: '9. Procedura de reclamație', p: 'Orice reclamație se transmite exclusiv în scris la adresa service@neofort-biz.ro, însoțită de fotografii clare ale defectului reclamat. În cazul unei reclamații nefondate (defecte inexistente, cauzate de utilizator, utilizare neconformă, întreținere defectuoasă sau abateri în limitele de toleranță legală), clientul suportă taxa de constatare: 500 lei + TVA per deplasare în raza municipiului București; 3 lei + TVA/km pentru deplasări în afara Bucureștiului. Termenul de remediere: maximum 15 zile calendaristice de la data constatării defectului de către tehnicianul NEOFORT BIZ SRL, cu excepția situațiilor independente de voința furnizorului (lanțuri de aprovizionare, forță majoră).' },
      { h: '10. Limitarea răspunderii', p: 'NEOFORT BIZ SRL nu răspunde pentru: întârzieri cauzate de forță majoră (calamități naturale, greve, restricții administrative), nerespectarea instrucțiunilor de utilizare și întreținere de către client, modificări aduse produselor de terți neautorizați. Răspunderea maximă a NEOFORT BIZ SRL față de un client este limitată la valoarea contractului aferent produselor/serviciilor care au generat prejudiciul.' },
      { h: '11. Proprietate intelectuală', p: 'Toate conținuturile site-ului neofort-biz.ro (texte, ghiduri tehnice, imagini, structura site-ului) sunt proprietatea NEOFORT BIZ SRL sau sunt utilizate cu acordul titularilor de drepturi. Reproducerea, distribuirea sau utilizarea comercială a oricărui conținut fără acordul scris al NEOFORT BIZ SRL este interzisă.' },
      { h: '12. Protecția datelor personale', p: 'Prelucrarea datelor cu caracter personal se realizează în conformitate cu Regulamentul UE 2016/679 (GDPR) și Politica de Confidențialitate publicată pe site. Datele furnizate sunt utilizate exclusiv pentru elaborarea ofertelor, executarea contractelor și comunicarea aferentă acestora.' },
      { h: '13. Legea aplicabilă și soluționarea litigiilor', p: 'Prezentele condiții generale sunt guvernate de legea română. Orice litigiu se va soluționa în primă instanță pe cale amiabilă. În cazul în care nu se ajunge la un acord, litigiul se supune competenței exclusive a instanțelor judecătorești din București. Clienții persoane fizice din Uniunea Europeană pot accesa platforma ODR a Comisiei Europene: ec.europa.eu/consumers/odr.' },
      { h: '14. Modificarea condițiilor generale', p: 'NEOFORT BIZ SRL poate modifica prezentele condiții generale în orice moment, cu publicarea versiunii actualizate pe site. Comenzile confirmate și în curs de execuție la data modificării rămân guvernate de condițiile valabile la data confirmării comenzii respective.' },
    ],
  },
  en: {
    label: 'Legal',
    h1: 'General Terms and Conditions',
    sub: 'General terms of sale, delivery, installation and warranty — NEOFORT BIZ SRL (VAT RO30324211). Last updated: May 2026.',
    title_meta: 'Terms and Conditions · Neofort BIZ',
    desc_meta: 'General terms and conditions Neofort BIZ SRL — firm order, delivery, installation, commercial warranty per OUG 140/2021 for Salamander PVC and Alumil aluminium windows.',
    sections: [
      { h: '1. Company information', p: 'NEOFORT BIZ SRL, registered at the Trade Registry under no. J40/6928/2012, VAT ID RO30324211, EUID ROONRC.J40/6928/2012, registered office: 11 Theodor Aman Pictor St., Sector 1, Bucharest 010776, Romania. Email: oferte@neofort-biz.ro · Phone: +40 752 443 435 · Hours: Mon–Fri 09:00–18:00.' },
      { h: '2. Nature of products — Firm order on individual specifications', p: 'All products supplied by NEOFORT BIZ SRL — Salamander PVC windows, Alumil aluminium windows, shading systems (Raffstore blinds, exterior shutters), accessories — are manufactured exclusively to the client\'s firm order, to the individual dimensions, configurations and technical specifications established by contract. Once the order is placed into production, products cannot be cancelled, modified, returned or substituted. There is no right of withdrawal or cancellation after order confirmation and production launch, pursuant to Art. 16(c) of Directive 2011/83/EU — express exception for goods made to the consumer\'s specifications or clearly personalised.' },
      { h: '3. Order process and contractual confirmation', p: 'Orders are initiated via the website contact form, phone or email. NEOFORT BIZ SRL issues an individualised price quote valid for 30 days. Client order confirmation and advance payment constitute irrevocable acceptance of the offer and trigger the production process. Delivery and installation lead time: 10–21 working days from advance payment confirmation, depending on order complexity.' },
      { h: '4. Prices, VAT and payment', p: 'Quoted prices are in Romanian Lei (RON), VAT excluded. 19% VAT is added per applicable fiscal law. Payment by bank transfer or cash at company premises. Minimum advance: 50% of contract value at order confirmation. Balance: upon installation completion or at delivery (orders without installation). NEOFORT BIZ SRL reserves the right to revise prices for currency fluctuations exceeding 5% from the quote date.' },
      { h: '5. Delivery and professional installation', p: 'Delivery to the address specified by the client in the confirmed order. Professional installation is carried out by NEOFORT BIZ SRL specialist teams per RAL standard, with pre-compressed butyl bands and three sealing zones (exterior, intermediate, interior). The client must ensure free access to the installation site and preparation of openings per the technical specifications communicated by the supplier. Connected works (demolition, masonry, finishing) are not included in the standard price and are contracted separately. Installation is finalised by signing the Works Acceptance Report.' },
      { h: '6. Commercial warranty', p: 'NEOFORT BIZ SRL provides commercial warranty in accordance with OUG no. 140/2021 and technical standards SR EN 12608, SR EN 12020-2, SR EN 1279, as follows: (a) Salamander PVC profiles: 5 years against manufacturing and material defects (chromatic stability, impact resistance, structural integrity); (b) Alumil aluminium profiles: 5 years against manufacturing defects (paint adhesion, corrosion resistance, profile integrity); (c) Roto/Winkhaus/GU hardware: 2 years against operating defects of opening/closing mechanisms, subject to periodic maintenance being carried out; (d) Thermal insulating glass: 5 years against seal failure (fogging between panes) and optical defects per SR EN 1279; (e) Professional installation (performed by NEOFORT BIZ SRL): 5 years against perimeter sealing of the frame against masonry. The warranty period runs from the date of signing the Works Acceptance Report or the date of submitting the fiscal invoice to SPV.' },
      { h: '7. Defect assessment — Applicable technical standards', p: 'Assessment of any claimed defect is carried out strictly in accordance with applicable technical regulations: (1) Visual inspection is performed from a minimum distance of 3 metres, in diffuse natural light, per SR EN 1279-1:2018 — defects not visible from this distance are considered compliant; (2) Dimensional deviations of up to ±2 mm and minor shade variations between production batches are accepted and do not constitute non-conformity, per SR EN 12608-1 and SR EN 12020-2; (3) Condensation on the interior glass surface (room-facing) is not a product defect — it results from excessive room humidity and insufficient ventilation. The warranty covers only condensation appearing between the panes of the insulating glass unit (seal failure defect).' },
      { h: '8. Warranty exclusions and voidance', p: 'The warranty is voided or does not apply in the following situations: (a) Failure to protect products during interior construction works — presence of construction dust (plaster, cement, lime, render) on hardware or profiles voids the warranty for closing mechanisms; (b) Cleaning with acidic, abrasive or solvent substances (acetone, thinner) or sharp objects; (c) Unauthorised interventions — fitting accessories (shutters, insect screens, sills) by third parties involving drilling or modifying profiles; (d) Forcing mechanisms — turning the handle with the window open or jamming with foreign objects; (e) Failure to carry out mandatory maintenance — hardware must be lubricated with silicone oil at least twice per year; (f) Non-payment of the full contract price — any outstanding balance suspends the warranty until full payment is made.' },
      { h: '9. Complaints procedure', p: 'All complaints must be submitted exclusively in writing to service@neofort-biz.ro, accompanied by clear photographs of the claimed defect. In the event of an unfounded complaint (non-existent defects, defects caused by the user, non-compliant use, improper maintenance or deviations within legal tolerance limits), the client bears the inspection fee: RON 500 + VAT per visit within Bucharest municipality; RON 3 + VAT/km for visits outside Bucharest. Remedy timeframe: maximum 15 calendar days from the date of defect confirmation by the NEOFORT BIZ SRL technician, except in situations beyond the supplier\'s control (supply chains, force majeure).' },
      { h: '10. Limitation of liability', p: 'NEOFORT BIZ SRL is not liable for: delays caused by force majeure (natural disasters, strikes, administrative restrictions), client failure to follow usage and maintenance instructions, modifications made to products by unauthorised third parties. Maximum liability is limited to the contract value of the products/services that generated the loss.' },
      { h: '11. Intellectual property', p: 'All content on neofort-biz.ro is the property of NEOFORT BIZ SRL or used with rights holders\' consent. Reproduction, distribution or commercial use without written consent from NEOFORT BIZ SRL is prohibited.' },
      { h: '12. Personal data protection', p: 'Personal data is processed in accordance with EU Regulation 2016/679 (GDPR) and the Privacy Policy published on the site. Data provided is used exclusively for preparing quotes, executing contracts and related communications.' },
      { h: '13. Applicable law and dispute resolution', p: 'These general conditions are governed by Romanian law. Disputes shall be resolved in the first instance amicably. If no agreement is reached, disputes are submitted to the exclusive jurisdiction of Bucharest courts. EU consumer clients may access the European Commission ODR platform: ec.europa.eu/consumers/odr.' },
      { h: '14. Amendment of general conditions', p: 'NEOFORT BIZ SRL may amend these general conditions at any time by publishing the updated version on the site. Orders confirmed and in progress at the date of amendment remain governed by the conditions valid at the date of order confirmation.' },
    ],
  },
  de: {
    label: 'Rechtliches',
    h1: 'Allgemeine Geschäftsbedingungen',
    sub: 'Allgemeine Verkaufs-, Liefer-, Montage- und Garantiebedingungen — NEOFORT BIZ SRL (USt-ID RO30324211). Letzte Aktualisierung: Mai 2026.',
    title_meta: 'AGB · Neofort BIZ',
    desc_meta: 'AGB Neofort BIZ SRL — Festbestellung, Lieferung, Montage, Handelsgarantie für Salamander Kunststoff- und Alumil Aluminiumfenster.',
    sections: [
      { h: '1. Unternehmensangaben', p: 'NEOFORT BIZ SRL, HR-Nr. J40/6928/2012, USt-ID RO30324211, EUID ROONRC.J40/6928/2012, Sitz: Str. Theodor Aman Pictor Nr. 11, Sektor 1, Bukarest 010776, Rumänien. E-Mail: oferte@neofort-biz.ro · Tel.: +40 752 443 435 · Mo–Fr 09:00–18:00.' },
      { h: '2. Produktcharakter — Festbestellung nach Individualspezifikation', p: 'Alle von NEOFORT BIZ SRL gelieferten Produkte — Salamander PVC-Fenster, Alumil Aluminiumfenster, Beschattungssysteme (Raffstore, Außenrollläden), Zubehör — werden ausschließlich als Festbestellung nach den individuellen Maßen, Konfigurationen und technischen Spezifikationen des Kunden gefertigt. Nach Produktionsstart können Aufträge nicht mehr storniert, geändert, zurückgegeben oder ersetzt werden. Es besteht kein Widerrufsrecht nach Auftragsbestätigung und Produktionsstart gemäß Art. 16 Buchst. c) der Richtlinie 2011/83/EU — ausdrückliche Ausnahme für nach Verbraucherspezifikation angefertigte oder eindeutig personalisierte Waren.' },
      { h: '3. Bestellprozess und vertragliche Bestätigung', p: 'Bestellungen per Kontaktformular, Telefon oder E-Mail. NEOFORT BIZ SRL sendet ein individuelles Angebot, gültig 30 Tage. Auftragsbestätigung und Anzahlung durch den Kunden gelten als unwiderrufliche Angebotsannahme und lösen die Produktion aus. Liefer- und Montagezeit: 10–21 Werktage ab Anzahlungseingang.' },
      { h: '4. Preise, MwSt. und Zahlung', p: 'Angebotspreise in RON ohne MwSt. 19% MwSt. wird hinzugefügt. Zahlung per Banküberweisung oder bar. Mindestanzahlung 50% bei Bestätigung; Restbetrag nach Montageabschluss oder Lieferung. Preisanpassung möglich bei Kursschwankungen über 5%.' },
      { h: '5. Lieferung und Fachmontage', p: 'Lieferung an die angegebene Adresse. Fachmontage durch NEOFORT BIZ SRL nach RAL-Standard mit vorkomprimierten Butylbändern und drei Dichtungszonen. Kunde stellt freien Zugang und vorbereitete Öffnungen sicher. Nebenarbeiten werden separat vereinbart. Abnahme durch Unterzeichnung des Abnahmeprotokolls.' },
      { h: '6. Handelsgarantie', p: 'NEOFORT BIZ SRL gewährt Handelsgarantie gemäß OUG Nr. 140/2021 und SR EN 12608, SR EN 12020-2, SR EN 1279: (a) Salamander PVC-Profile: 5 Jahre gegen Material- und Herstellungsfehler; (b) Alumil Aluminiumprofile: 5 Jahre gegen Herstellungsfehler; (c) Roto/Winkhaus/GU-Beschläge: 2 Jahre gegen Funktionsfehler bei regelmäßiger Pflege; (d) Isolierglas: 5 Jahre gegen Versiegelungsversagen und optische Fehler per SR EN 1279; (e) Fachmontage (durch NEOFORT BIZ SRL): 5 Jahre gegen Abdichtungsmängel. Garantiebeginn: Unterzeichnung des Abnahmeprotokolls oder Datum der Rechnungseinreichung in SPV.' },
      { h: '7. Mängelbeurteilung — Anzuwendende technische Normen', p: 'Beurteilung gemeldeter Mängel nach geltenden technischen Vorschriften: (1) Sichtprüfung aus mindestens 3 Metern unter natürlichem Streulicht per SR EN 1279-1:2018; (2) Maßabweichungen bis ±2 mm und geringe Farbtönungsunterschiede zwischen Produktionschargen sind zulässig per SR EN 12608-1 und SR EN 12020-2; (3) Kondensat an der Raumseite der Scheibe ist kein Produktfehler — Ursache ist übermäßige Raumfeuchtigkeit und unzureichende Lüftung. Garantiert wird nur Kondensat zwischen den Scheiben (Versiegelungsversagen).' },
      { h: '8. Garantieausschlüsse und -verlust', p: 'Garantieverlust bei: (a) Unzureichendem Schutz während Bauarbeiten — Baustaub auf Beschlägen oder Profilen; (b) Reinigung mit aggressiven, schleifenden oder lösungsmittelhaltigen Mitteln; (c) Unbefugten Eingriffen Dritter (Bohren, Modifikationen); (d) Gewaltsamer Betätigung (Griff bei geöffnetem Fenster drehen, Blockieren); (e) Fehlender Pflege — Beschläge müssen mindestens 2x jährlich mit Silikonöl geschmiert werden; (f) Ausstehenden Restzahlungen — die Garantie ruht bis zur vollständigen Bezahlung.' },
      { h: '9. Reklamationsverfahren', p: 'Reklamationen ausschließlich schriftlich an service@neofort-biz.ro mit Fotos. Bei unbegründeter Reklamation trägt der Kunde die Anfahrtkosten: 500 RON + MwSt. je Einsatz in Bukarest; 3 RON + MwSt./km außerhalb Bukarests. Behebungsfrist: max. 15 Kalendertage ab Mängelbestätigung durch NEOFORT BIZ SRL-Techniker, außer bei lieferkettenabhängigen Situationen oder höherer Gewalt.' },
      { h: '10. Haftungsbeschränkung', p: 'NEOFORT BIZ SRL haftet nicht für Verzögerungen durch höhere Gewalt, Nichtbeachtung der Gebrauchsanleitung oder Eingriffe unbefugter Dritter. Maximale Haftung begrenzt auf den Auftragswert der schadensverursachenden Produkte/Leistungen.' },
      { h: '11. Geistiges Eigentum', p: 'Alle Inhalte von neofort-biz.ro sind Eigentum von NEOFORT BIZ SRL. Vervielfältigung oder kommerzielle Nutzung ohne schriftliche Genehmigung ist untersagt.' },
      { h: '12. Datenschutz', p: 'Personenbezogene Daten werden gemäß DSGVO (EU 2016/679) und der Datenschutzerklärung auf der Website verarbeitet. Daten werden ausschließlich für Angebotserstellung und Vertragsabwicklung genutzt.' },
      { h: '13. Anwendbares Recht und Streitigkeiten', p: 'Diese AGB unterliegen rumänischem Recht. Streitigkeiten werden zunächst gütlich beigelegt; bei Scheitern sind die Bukarester Gerichte ausschließlich zuständig. EU-Verbraucher können die ODR-Plattform nutzen: ec.europa.eu/consumers/odr.' },
      { h: '14. Änderung der AGB', p: 'NEOFORT BIZ SRL kann diese AGB jederzeit ändern. Bestätigte und laufende Aufträge bleiben den zum Bestellzeitpunkt geltenden Bedingungen unterworfen.' },
    ],
  },
  fr: {
    label: 'Légal',
    h1: 'Conditions Générales de Vente',
    sub: 'Conditions générales de vente, livraison, pose et garantie — NEOFORT BIZ SRL (TVA RO30324211). Dernière mise à jour : Mai 2026.',
    title_meta: 'CGV · Neofort BIZ',
    desc_meta: 'CGV Neofort BIZ SRL — commande ferme, livraison, pose, garantie commerciale pour fenêtres PVC Salamander et aluminium Alumil.',
    sections: [
      { h: '1. Informations sur la société', p: 'NEOFORT BIZ SRL, RC n° J40/6928/2012, TVA RO30324211, EUID ROONRC.J40/6928/2012, siège : 11 rue Theodor Aman Pictor, Secteur 1, Bucarest 010776, Roumanie. E-mail : oferte@neofort-biz.ro · Tél. : +40 752 443 435 · Lun–Ven 09h00–18h00.' },
      { h: '2. Nature des produits — Commande ferme sur spécifications individuelles', p: "Tous les produits fournis par NEOFORT BIZ SRL — menuiseries PVC Salamander, menuiseries aluminium Alumil, systèmes d'occultation (stores Raffstore, volets roulants), accessoires — sont fabriqués exclusivement sur commande ferme du client, aux dimensions, configurations et spécifications techniques individuelles définies par contrat. Une fois la commande lancée en production, les produits ne peuvent être ni annulés, ni modifiés, ni retournés, ni substitués. Il n'existe aucun droit de rétractation ou d'annulation après confirmation de commande et lancement en production, conformément à l'art. 16(c) de la Directive 2011/83/UE — exception expresse pour les biens confectionnés selon les spécifications du consommateur ou nettement personnalisés." },
      { h: '3. Processus de commande et confirmation contractuelle', p: "Commandes par formulaire de contact, téléphone ou e-mail. NEOFORT BIZ SRL émet un devis individualisé valable 30 jours. La confirmation de commande par le client et le versement de l'acompte constituent une acceptation irrévocable du devis et déclenchent la production. Délai de livraison et pose : 10–21 jours ouvrables à compter de la confirmation du paiement." },
      { h: '4. Prix, TVA et modalités de paiement', p: "Prix en Lei roumains (RON) HT. TVA 19% ajoutée. Paiement par virement ou espèces. Acompte minimum 50% à la confirmation ; solde à la fin de la pose ou livraison. Révision possible pour fluctuations de change supérieures à 5%." },
      { h: '5. Livraison et pose professionnelle', p: "Livraison à l'adresse indiquée. Pose professionnelle par les équipes NEOFORT BIZ SRL selon la norme RAL, avec bandes précomprimées butyliques et trois zones d'étanchéité. Client responsable de l'accès libre et de la préparation des baies. Travaux connexes contractés séparément. Réception par signature du procès-verbal de réception." },
      { h: '6. Garantie commerciale', p: "NEOFORT BIZ SRL accorde une garantie commerciale conformément à OUG n° 140/2021 et aux normes SR EN 12608, SR EN 12020-2, SR EN 1279 : (a) Profilés PVC Salamander : 5 ans contre défauts de fabrication et de matériau ; (b) Profilés aluminium Alumil : 5 ans contre défauts de fabrication ; (c) Quincaillerie Roto/Winkhaus/GU : 2 ans contre défauts de fonctionnement, sous réserve d'entretien périodique ; (d) Vitrage isolant : 5 ans contre défauts d'étanchéité et défauts optiques per SR EN 1279 ; (e) Pose professionnelle (effectuée par NEOFORT BIZ SRL) : 5 ans contre défauts d'étanchéité périphérique. Début de garantie : signature du PV de réception ou date de soumission de la facture au SPV." },
      { h: '7. Évaluation des défauts — Normes techniques applicables', p: "Évaluation des défauts strictement selon les réglementations techniques en vigueur : (1) Inspection visuelle depuis minimum 3 mètres sous lumière naturelle diffuse per SR EN 1279-1:2018 ; (2) Écarts dimensionnels jusqu'à ±2 mm et légères variations de teinte entre lots sont admis per SR EN 12608-1 et SR EN 12020-2 ; (3) La condensation sur la face intérieure du vitrage n'est pas un défaut produit — elle résulte d'une humidité excessive et d'une ventilation insuffisante. La garantie couvre uniquement la condensation entre les feuilles du vitrage isolant (défaut d'étanchéité)." },
      { h: '8. Exclusions et nullité de la garantie', p: "La garantie est annulée ou ne s'applique pas dans les cas suivants : (a) Absence de protection pendant les travaux — présence de poussières de construction sur quincaillerie ou profilés ; (b) Nettoyage avec produits acides, abrasifs ou solvants ; (c) Interventions non autorisées par des tiers (perçage, modification des profilés) ; (d) Forçage des mécanismes — rotation de la poignée fenêtre ouverte, blocage par corps étrangers ; (e) Absence d'entretien obligatoire — quincaillerie à graisser à l'huile silicone minimum 2 fois par an ; (f) Solde impayé — toute somme restante suspend la garantie jusqu'au paiement intégral." },
      { h: '9. Procédure de réclamation', p: "Réclamations exclusivement par écrit à service@neofort-biz.ro avec photos. En cas de réclamation non fondée, le client supporte les frais de déplacement : 500 RON + TVA par intervention à Bucarest ; 3 RON + TVA/km hors Bucarest. Délai de réparation : 15 jours calendaires maximum à compter de la constatation du défaut, sauf situation indépendante de la volonté du fournisseur." },
      { h: '10. Limitation de responsabilité', p: "NEOFORT BIZ SRL n'est pas responsable des retards par force majeure, du non-respect des instructions d'utilisation, ni des modifications par des tiers non autorisés. Responsabilité maximale limitée à la valeur du contrat." },
      { h: '11. Propriété intellectuelle', p: "Tous les contenus de neofort-biz.ro sont la propriété de NEOFORT BIZ SRL. Toute reproduction ou utilisation commerciale sans accord écrit est interdite." },
      { h: '12. Protection des données personnelles', p: "Les données personnelles sont traitées conformément au RGPD (UE 2016/679) et à la politique de confidentialité publiée sur le site." },
      { h: '13. Droit applicable et règlement des litiges', p: "Ces CGV sont régies par le droit roumain. Résolution amiable en premier lieu ; à défaut, tribunaux de Bucarest compétents exclusivement. Consommateurs UE : plateforme ODR ec.europa.eu/consumers/odr." },
      { h: '14. Modification des CGV', p: "NEOFORT BIZ SRL peut modifier ces CGV à tout moment. Les commandes confirmées et en cours restent régies par les conditions en vigueur à la date de confirmation." },
    ],
  },
  es: {
    label: 'Legal',
    h1: 'Términos y Condiciones Generales',
    sub: 'Condiciones generales de venta, entrega, instalación y garantía — NEOFORT BIZ SRL (CIF RO30324211). Última actualización: Mayo 2026.',
    title_meta: 'Términos y Condiciones · Neofort BIZ',
    desc_meta: 'Términos y condiciones Neofort BIZ SRL — pedido firme, entrega, instalación, garantía comercial para ventanas PVC Salamander y aluminio Alumil.',
    sections: [
      { h: '1. Información de la empresa', p: 'NEOFORT BIZ SRL, Reg. Mercantil J40/6928/2012, CIF RO30324211, EUID ROONRC.J40/6928/2012, domicilio: C/ Theodor Aman Pictor 11, Sector 1, Bucarest 010776, Rumanía. E-mail: oferte@neofort-biz.ro · Tel.: +40 752 443 435 · Lun–Vie 09:00–18:00.' },
      { h: '2. Naturaleza de los productos — Pedido firme sobre especificaciones individuales', p: 'Todos los productos suministrados por NEOFORT BIZ SRL — carpintería PVC Salamander, carpintería aluminio Alumil, sistemas de sombreado (persianas Raffstore, cierres enrollables), accesorios — se fabrican exclusivamente sobre pedido firme del cliente, a las dimensiones, configuraciones y especificaciones técnicas individuales establecidas por contrato. Una vez lanzado el pedido a producción, los productos no pueden cancelarse, modificarse, devolverse ni sustituirse. No existe derecho de desistimiento ni cancelación tras la confirmación del pedido y lanzamiento a producción, conforme al art. 16(c) de la Directiva 2011/83/UE — excepción expresa para bienes confeccionados según las especificaciones del consumidor o claramente personalizados.' },
      { h: '3. Proceso de pedido y confirmación contractual', p: 'Pedidos por formulario de contacto, teléfono o e-mail. NEOFORT BIZ SRL emite un presupuesto individualizado válido 30 días. La confirmación del pedido y el pago del anticipo constituyen aceptación irrevocable del presupuesto y activan la producción. Plazo de entrega e instalación: 10–21 días hábiles desde la confirmación del pago.' },
      { h: '4. Precios, IVA y pago', p: 'Precios en Lei rumanos (RON) sin IVA. IVA 19% añadido. Pago por transferencia o efectivo. Anticipo mínimo 50% a la confirmación; saldo al finalizar la instalación o entrega. Revisión posible ante fluctuaciones de cambio superiores al 5%.' },
      { h: '5. Entrega e instalación profesional', p: 'Entrega en la dirección indicada. Instalación profesional por equipos NEOFORT BIZ SRL según norma RAL, con bandas precomprimidas butílicas y tres zonas de sellado. Cliente responsable del acceso libre y preparación de huecos. Trabajos conexos contratados por separado. Recepción mediante firma del acta de recepción.' },
      { h: '6. Garantía comercial', p: 'NEOFORT BIZ SRL otorga garantía comercial conforme a OUG n.º 140/2021 y normas SR EN 12608, SR EN 12020-2, SR EN 1279: (a) Perfiles PVC Salamander: 5 años contra defectos de fabricación y material; (b) Perfiles aluminio Alumil: 5 años contra defectos de fabricación; (c) Herraje Roto/Winkhaus/GU: 2 años contra defectos de funcionamiento con mantenimiento periódico; (d) Vidrio aislante: 5 años contra fallos de sellado y defectos ópticos per SR EN 1279; (e) Instalación profesional (por NEOFORT BIZ SRL): 5 años contra defectos de sellado perimetral. Inicio de garantía: firma del acta de recepción o fecha de presentación de la factura al SPV.' },
      { h: '7. Evaluación de defectos — Normas técnicas aplicables', p: 'Evaluación de defectos estrictamente según normativa técnica vigente: (1) Inspección visual desde mínimo 3 metros bajo luz natural difusa per SR EN 1279-1:2018; (2) Desviaciones dimensionales hasta ±2 mm y ligeras variaciones de tono entre lotes son admitidas per SR EN 12608-1 y SR EN 12020-2; (3) La condensación en la cara interior del vidrio no es un defecto del producto — resulta de humedad excesiva y ventilación insuficiente. La garantía cubre exclusivamente la condensación entre las láminas del vidrio aislante (fallo de sellado).' },
      { h: '8. Exclusiones y nulidad de la garantía', p: 'La garantía queda anulada o no se aplica en los siguientes casos: (a) Falta de protección durante obras — presencia de polvo de construcción en herraje o perfiles; (b) Limpieza con productos ácidos, abrasivos o disolventes; (c) Intervenciones no autorizadas por terceros (perforación, modificación de perfiles); (d) Forzado de mecanismos — girar la manija con la ventana abierta, bloqueo con objetos extraños; (e) Ausencia de mantenimiento obligatorio — herraje debe engrasarse con aceite de silicona mínimo 2 veces al año; (f) Saldo pendiente de pago — cualquier importe pendiente suspende la garantía hasta el pago íntegro.' },
      { h: '9. Procedimiento de reclamación', p: 'Reclamaciones exclusivamente por escrito a service@neofort-biz.ro con fotografías. En caso de reclamación infundada, el cliente asume los gastos de desplazamiento: 500 RON + IVA por visita en Bucarest; 3 RON + IVA/km fuera de Bucarest. Plazo de subsanación: máximo 15 días naturales desde la constatación del defecto, salvo situaciones ajenas al proveedor.' },
      { h: '10. Limitación de responsabilidad', p: 'NEOFORT BIZ SRL no responde por retrasos por fuerza mayor, incumplimiento de instrucciones de uso o modificaciones por terceros no autorizados. Responsabilidad máxima limitada al valor del contrato.' },
      { h: '11. Propiedad intelectual', p: 'Todos los contenidos de neofort-biz.ro son propiedad de NEOFORT BIZ SRL. Cualquier reproducción o uso comercial sin autorización escrita está prohibido.' },
      { h: '12. Protección de datos personales', p: 'Los datos personales se tratan conforme al RGPD (UE 2016/679) y la política de privacidad publicada en el sitio.' },
      { h: '13. Ley aplicable y resolución de litigios', p: 'Estas condiciones se rigen por la ley rumana. Resolución amistosa en primer lugar; en su defecto, tribunales de Bucarest con competencia exclusiva. Consumidores UE: plataforma ODR ec.europa.eu/consumers/odr.' },
      { h: '14. Modificación de las condiciones generales', p: 'NEOFORT BIZ SRL puede modificar estas condiciones en cualquier momento. Los pedidos confirmados y en curso quedan regidos por las condiciones vigentes en la fecha de confirmación.' },
    ],
  },
  it: {
    label: 'Legale',
    h1: 'Termini e Condizioni Generali',
    sub: 'Condizioni generali di vendita, consegna, installazione e garanzia — NEOFORT BIZ SRL (P.IVA RO30324211). Ultimo aggiornamento: Maggio 2026.',
    title_meta: 'Termini e Condizioni · Neofort BIZ',
    desc_meta: 'Termini e condizioni Neofort BIZ SRL — ordine fermo, consegna, installazione, garanzia commerciale per infissi PVC Salamander e alluminio Alumil.',
    sections: [
      { h: '1. Informazioni aziendali', p: 'NEOFORT BIZ SRL, Reg. Imprese J40/6928/2012, P.IVA RO30324211, EUID ROONRC.J40/6928/2012, sede: Via Theodor Aman Pictor 11, Settore 1, Bucarest 010776, Romania. E-mail: oferte@neofort-biz.ro · Tel.: +40 752 443 435 · Lun–Ven 09:00–18:00.' },
      { h: '2. Natura dei prodotti — Ordine fermo su specifiche individuali', p: `Tutti i prodotti forniti da NEOFORT BIZ SRL — infissi PVC Salamander, infissi alluminio Alumil, sistemi di oscuramento (veneziane Raffstore, tapparelle), accessori — sono fabbricati esclusivamente su ordine fermo del cliente, alle dimensioni, configurazioni e specifiche tecniche individuali stabilite dal contratto. Una volta avviato l'ordine in produzione, i prodotti non possono essere annullati, modificati, restituiti o sostituiti. Non esiste diritto di recesso o cancellazione dopo la conferma dell'ordine e l'avvio della produzione, ai sensi dell'art. 16(c) della Direttiva 2011/83/UE — eccezione espressa per beni confezionati secondo le specifiche del consumatore o chiaramente personalizzati.` },
      { h: '3. Processo d\'ordine e conferma contrattuale', p: `Ordini tramite modulo di contatto, telefono o e-mail. NEOFORT BIZ SRL emette un preventivo individualizzato valido 30 giorni. La conferma dell'ordine e il versamento dell'acconto costituiscono accettazione irrevocabile del preventivo e avviano la produzione. Tempi di consegna e installazione: 10–21 giorni lavorativi dalla conferma del pagamento.` },
      { h: '4. Prezzi, IVA e pagamento', p: `Prezzi in Lei rumeni (RON) IVA esclusa. IVA 19% aggiunta. Pagamento tramite bonifico o contanti. Acconto minimo 50% alla conferma; saldo al termine dell'installazione o consegna. Revisione possibile per fluttuazioni valutarie superiori al 5%.` },
      { h: '5. Consegna e installazione professionale', p: `Consegna all'indirizzo indicato. Installazione professionale da parte dei team NEOFORT BIZ SRL secondo norma RAL, con nastri precompressi butilici e tre zone di sigillatura. Cliente responsabile dell'accesso libero e della preparazione delle aperture. Lavori connessi contrattati separatamente. Accettazione tramite firma del verbale di collaudo.` },
      { h: '6. Garanzia commerciale', p: `NEOFORT BIZ SRL concede garanzia commerciale ai sensi di OUG n. 140/2021 e norme SR EN 12608, SR EN 12020-2, SR EN 1279: (a) Profili PVC Salamander: 5 anni contro difetti di fabbricazione e materiale; (b) Profili alluminio Alumil: 5 anni contro difetti di fabbricazione; (c) Ferramenta Roto/Winkhaus/GU: 2 anni contro difetti di funzionamento con manutenzione periodica; (d) Vetrocamera: 5 anni contro difetti di tenuta e difetti ottici per SR EN 1279; (e) Installazione professionale (eseguita da NEOFORT BIZ SRL): 5 anni contro difetti di sigillatura perimetrale. Inizio garanzia: firma del verbale di collaudo o data di presentazione della fattura all'SPV.` },
      { h: '7. Valutazione dei difetti — Norme tecniche applicabili', p: `Valutazione dei difetti strettamente secondo le normative tecniche vigenti: (1) Ispezione visiva da minimo 3 metri sotto luce naturale diffusa per SR EN 1279-1:2018; (2) Scostamenti dimensionali fino a ±2 mm e lievi variazioni di tonalità tra lotti sono ammessi per SR EN 12608-1 e SR EN 12020-2; (3) La condensa sulla superficie interna del vetro non è un difetto del prodotto — è conseguenza di umidità eccessiva e ventilazione insufficiente. La garanzia copre esclusivamente la condensa tra le lastre della vetrocamera (difetto di sigillatura).` },
      { h: '8. Esclusioni e decadenza della garanzia', p: `La garanzia decade o non si applica nei seguenti casi: (a) Mancata protezione durante lavori edili — presenza di polvere da costruzione su ferramenta o profili; (b) Pulizia con prodotti acidi, abrasivi o solventi; (c) Interventi non autorizzati da terzi (foratura, modifica dei profili); (d) Forzatura dei meccanismi — rotazione della maniglia con finestra aperta, blocco con corpi estranei; (e) Assenza di manutenzione obbligatoria — la ferramenta deve essere lubrificata con olio silicone minimo 2 volte all'anno; (f) Saldo non pagato — qualsiasi importo residuo sospende la garanzia fino al pagamento integrale.` },
      { h: '9. Procedura di reclamo', p: `Reclami esclusivamente per iscritto a service@neofort-biz.ro con fotografie. In caso di reclamo infondato, il cliente sostiene i costi di trasferta: 500 RON + IVA per intervento a Bucarest; 3 RON + IVA/km fuori Bucarest. Termine di riparazione: massimo 15 giorni di calendario dalla constatazione del difetto, salvo situazioni indipendenti dalla volontà del fornitore.` },
      { h: '10. Limitazione di responsabilità', p: `NEOFORT BIZ SRL non è responsabile per ritardi da forza maggiore, mancato rispetto delle istruzioni d'uso o modifiche da terzi non autorizzati. Responsabilità massima limitata al valore del contratto.` },
      { h: '11. Proprietà intellettuale', p: 'Tutti i contenuti di neofort-biz.ro sono di proprietà di NEOFORT BIZ SRL. Qualsiasi riproduzione o utilizzo commerciale senza autorizzazione scritta è vietato.' },
      { h: '12. Protezione dei dati personali', p: `I dati personali sono trattati conformemente al GDPR (UE 2016/679) e all'informativa sulla privacy pubblicata sul sito.` },
      { h: '13. Legge applicabile e risoluzione delle controversie', p: 'Queste condizioni sono disciplinate dalla legge rumena. Risoluzione amichevole in prima istanza; in caso di insuccesso, tribunali di Bucarest con competenza esclusiva. Consumatori UE: piattaforma ODR ec.europa.eu/consumers/odr.' },
      { h: '14. Modifica delle condizioni generali', p: `NEOFORT BIZ SRL può modificare queste condizioni in qualsiasi momento. Gli ordini confermati e in corso restano disciplinati dalle condizioni vigenti alla data di conferma.` },
    ],
  },
};

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const ui = UI[locale] || UI.ro;
  const slug = SLUGS[locale] || SLUGS.ro;
  const langs = {};
  Object.entries(SLUGS).forEach(([l, sl]) => { langs[l] = `${BASE}/${l}/${sl}`; });
  return {
    title: ui.title_meta,
    description: ui.desc_meta,
    alternates: { canonical: `${BASE}/${locale}/${slug}`, languages: langs },
    robots: { index: false, follow: false },
  };
}

export default async function TermeniPage({ params }) {
  const { locale } = await params;
  const ui = UI[locale] || UI.ro;
  return (
    <article style={{ maxWidth: '800px', margin: '0 auto', padding: '60px 24px 80px' }}>
      <header style={{ marginBottom: '48px', borderBottom: '1px solid #e8e8e8', paddingBottom: '32px' }}>
        <span style={{ fontFamily:'Barlow Condensed,sans-serif', fontSize:'.62rem', letterSpacing:'.2em', textTransform:'uppercase', color:'#767676', display:'block', marginBottom:'12px' }}>
          {ui.label}
        </span>
        <h1 style={{ fontFamily:'Barlow Condensed,sans-serif', fontWeight:500, fontSize:'2rem', letterSpacing:'.02em', color:'#1a1a1a', marginBottom:'12px', lineHeight:1.2 }}>
          {ui.h1}
        </h1>
        <p style={{ fontFamily:'Barlow,sans-serif', fontSize:'.82rem', fontWeight:300, color:'#767676', lineHeight:1.6 }}>
          {ui.sub}
        </p>
      </header>
      {ui.sections.map((sec, i) => (
        <section key={i} style={{ marginBottom:'32px' }}>
          <h2 style={{ fontFamily:'Barlow Condensed,sans-serif', fontWeight:500, fontSize:'1rem', letterSpacing:'.04em', color:'#1a1a1a', marginBottom:'10px', textTransform:'uppercase' }}>
            {sec.h}
          </h2>
          <p style={{ fontFamily:'Barlow,sans-serif', fontSize:'.9rem', fontWeight:300, color:'#444', lineHeight:1.75 }}>
            {sec.p}
          </p>
        </section>
      ))}
    </article>
  );
}
